# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brocade_collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brocade_interface_pb2 as brocade__interface__pb2
import brocade_systemutilization_pb2 as brocade__systemutilization__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='brocade_collector.proto',
  package='com.brocade.telemetry.collector',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x62rocade_collector.proto\x12\x1f\x63om.brocade.telemetry.collector\x1a\x17\x62rocade_interface.proto\x1a\x1f\x62rocade_systemutilization.proto\"\xfe\x02\n\x11\x43ollectorResponse\x12T\n\x0cprofile_type\x18\x01 \x01(\x0e\x32>.com.brocade.telemetry.collector.CollectorResponse.ProfileType\x12W\n\x12interface_response\x18\x02 \x01(\x0b\x32\x39.com.brocade.telemetry.interface.InterfaceProfileResponseH\x00\x12p\n\x1bsystem_utilization_response\x18\x03 \x01(\x0b\x32I.com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponseH\x00\"4\n\x0bProfileType\x12\r\n\tinterface\x10\x00\x12\x16\n\x12system_utilization\x10\x01\x42\x12\n\x10profile_responseb\x06proto3')
  ,
  dependencies=[brocade__interface__pb2.DESCRIPTOR,brocade__systemutilization__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COLLECTORRESPONSE_PROFILETYPE = _descriptor.EnumDescriptor(
  name='ProfileType',
  full_name='com.brocade.telemetry.collector.CollectorResponse.ProfileType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='interface', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='system_utilization', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_COLLECTORRESPONSE_PROFILETYPE)


_COLLECTORRESPONSE = _descriptor.Descriptor(
  name='CollectorResponse',
  full_name='com.brocade.telemetry.collector.CollectorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_type', full_name='com.brocade.telemetry.collector.CollectorResponse.profile_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interface_response', full_name='com.brocade.telemetry.collector.CollectorResponse.interface_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_utilization_response', full_name='com.brocade.telemetry.collector.CollectorResponse.system_utilization_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COLLECTORRESPONSE_PROFILETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='profile_response', full_name='com.brocade.telemetry.collector.CollectorResponse.profile_response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=119,
  serialized_end=501,
)

_COLLECTORRESPONSE.fields_by_name['profile_type'].enum_type = _COLLECTORRESPONSE_PROFILETYPE
_COLLECTORRESPONSE.fields_by_name['interface_response'].message_type = brocade__interface__pb2._INTERFACEPROFILERESPONSE
_COLLECTORRESPONSE.fields_by_name['system_utilization_response'].message_type = brocade__systemutilization__pb2._SYSTEMUTILIZATIONPROFILERESPONSE
_COLLECTORRESPONSE_PROFILETYPE.containing_type = _COLLECTORRESPONSE
_COLLECTORRESPONSE.oneofs_by_name['profile_response'].fields.append(
  _COLLECTORRESPONSE.fields_by_name['interface_response'])
_COLLECTORRESPONSE.fields_by_name['interface_response'].containing_oneof = _COLLECTORRESPONSE.oneofs_by_name['profile_response']
_COLLECTORRESPONSE.oneofs_by_name['profile_response'].fields.append(
  _COLLECTORRESPONSE.fields_by_name['system_utilization_response'])
_COLLECTORRESPONSE.fields_by_name['system_utilization_response'].containing_oneof = _COLLECTORRESPONSE.oneofs_by_name['profile_response']
DESCRIPTOR.message_types_by_name['CollectorResponse'] = _COLLECTORRESPONSE

CollectorResponse = _reflection.GeneratedProtocolMessageType('CollectorResponse', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTORRESPONSE,
  __module__ = 'brocade_collector_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.collector.CollectorResponse)
  ))
_sym_db.RegisterMessage(CollectorResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
