# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/brocade_interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/brocade_interface.proto',
  package='com.brocade.telemetry.interface',
  syntax='proto3',
  serialized_pb=_b('\n\x1eprotos/brocade_interface.proto\x12\x1f\x63om.brocade.telemetry.interface\"\x88\x04\n\x11InterfaceCounters\x12\x0f\n\x07if_name\x18\x01 \x01(\t\x12\x10\n\x08if_index\x18\x02 \x01(\x04\x12\x0f\n\x07in_pkts\x18\x03 \x01(\x04\x12\x17\n\x0fin_unicast_pkts\x18\x04 \x01(\x04\x12\x19\n\x11in_broadcast_pkts\x18\x05 \x01(\x04\x12\x19\n\x11in_multicast_pkts\x18\x06 \x01(\x04\x12\x1a\n\x12in_pkts_per_second\x18\x07 \x01(\x04\x12\x14\n\x0cin_bandwidth\x18\x08 \x01(\x04\x12\x11\n\tin_octets\x18\t \x01(\x04\x12\x11\n\tin_errors\x18\n \x01(\x04\x12\x15\n\rin_crc_errors\x18\x0b \x01(\x04\x12\x13\n\x0bin_discards\x18\x0c \x01(\x04\x12\x10\n\x08out_pkts\x18\r \x01(\x04\x12\x18\n\x10out_unicast_pkts\x18\x0e \x01(\x04\x12\x1a\n\x12out_broadcast_pkts\x18\x0f \x01(\x04\x12\x1a\n\x12out_multicast_pkts\x18\x10 \x01(\x04\x12\x1b\n\x13out_pkts_per_second\x18\x11 \x01(\x04\x12\x15\n\rout_bandwidth\x18\x12 \x01(\x04\x12\x12\n\nout_octets\x18\x13 \x01(\x04\x12\x12\n\nout_errors\x18\x14 \x01(\x04\x12\x16\n\x0eout_crc_errors\x18\x15 \x01(\x04\x12\x14\n\x0cout_discards\x18\x16 \x01(\x04\"/\n\x17InterfaceProfileRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\"\x80\x01\n\x18InterfaceProfileResponse\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12N\n\x12interface_counters\x18\x02 \x03(\x0b\x32\x32.com.brocade.telemetry.interface.InterfaceCounters2\xa7\x01\n\x10InterfaceService\x12\x92\x01\n\x17ListInterfaceStatistics\x12\x38.com.brocade.telemetry.interface.InterfaceProfileRequest\x1a\x39.com.brocade.telemetry.interface.InterfaceProfileResponse\"\x00\x30\x01\x42\x02H\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INTERFACECOUNTERS = _descriptor.Descriptor(
  name='InterfaceCounters',
  full_name='com.brocade.telemetry.interface.InterfaceCounters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_name', full_name='com.brocade.telemetry.interface.InterfaceCounters.if_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='if_index', full_name='com.brocade.telemetry.interface.InterfaceCounters.if_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_pkts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_unicast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_unicast_pkts', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_broadcast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_broadcast_pkts', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_multicast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_multicast_pkts', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_pkts_per_second', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_pkts_per_second', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_bandwidth', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_bandwidth', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_octets', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_octets', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_errors', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_errors', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_crc_errors', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_crc_errors', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_discards', full_name='com.brocade.telemetry.interface.InterfaceCounters.in_discards', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_pkts', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_unicast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_unicast_pkts', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_broadcast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_broadcast_pkts', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_multicast_pkts', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_multicast_pkts', index=15,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_pkts_per_second', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_pkts_per_second', index=16,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_bandwidth', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_bandwidth', index=17,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_octets', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_octets', index=18,
      number=19, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_errors', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_errors', index=19,
      number=20, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_crc_errors', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_crc_errors', index=20,
      number=21, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_discards', full_name='com.brocade.telemetry.interface.InterfaceCounters.out_discards', index=21,
      number=22, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=588,
)


_INTERFACEPROFILEREQUEST = _descriptor.Descriptor(
  name='InterfaceProfileRequest',
  full_name='com.brocade.telemetry.interface.InterfaceProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='com.brocade.telemetry.interface.InterfaceProfileRequest.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=637,
)


_INTERFACEPROFILERESPONSE = _descriptor.Descriptor(
  name='InterfaceProfileResponse',
  full_name='com.brocade.telemetry.interface.InterfaceProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='com.brocade.telemetry.interface.InterfaceProfileResponse.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interface_counters', full_name='com.brocade.telemetry.interface.InterfaceProfileResponse.interface_counters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=768,
)

_INTERFACEPROFILERESPONSE.fields_by_name['interface_counters'].message_type = _INTERFACECOUNTERS
DESCRIPTOR.message_types_by_name['InterfaceCounters'] = _INTERFACECOUNTERS
DESCRIPTOR.message_types_by_name['InterfaceProfileRequest'] = _INTERFACEPROFILEREQUEST
DESCRIPTOR.message_types_by_name['InterfaceProfileResponse'] = _INTERFACEPROFILERESPONSE

InterfaceCounters = _reflection.GeneratedProtocolMessageType('InterfaceCounters', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACECOUNTERS,
  __module__ = 'protos.brocade_interface_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.interface.InterfaceCounters)
  ))
_sym_db.RegisterMessage(InterfaceCounters)

InterfaceProfileRequest = _reflection.GeneratedProtocolMessageType('InterfaceProfileRequest', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACEPROFILEREQUEST,
  __module__ = 'protos.brocade_interface_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.interface.InterfaceProfileRequest)
  ))
_sym_db.RegisterMessage(InterfaceProfileRequest)

InterfaceProfileResponse = _reflection.GeneratedProtocolMessageType('InterfaceProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACEPROFILERESPONSE,
  __module__ = 'protos.brocade_interface_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.interface.InterfaceProfileResponse)
  ))
_sym_db.RegisterMessage(InterfaceProfileResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\002'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class InterfaceServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListInterfaceStatistics = channel.unary_stream(
        '/com.brocade.telemetry.interface.InterfaceService/ListInterfaceStatistics',
        request_serializer=InterfaceProfileRequest.SerializeToString,
        response_deserializer=InterfaceProfileResponse.FromString,
        )


class InterfaceServiceServicer(object):

  def ListInterfaceStatistics(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InterfaceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListInterfaceStatistics': grpc.unary_stream_rpc_method_handler(
          servicer.ListInterfaceStatistics,
          request_deserializer=InterfaceProfileRequest.FromString,
          response_serializer=InterfaceProfileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.brocade.telemetry.interface.InterfaceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaInterfaceServiceServicer(object):
  def ListInterfaceStatistics(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaInterfaceServiceStub(object):
  def ListInterfaceStatistics(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()


def beta_create_InterfaceService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('com.brocade.telemetry.interface.InterfaceService', 'ListInterfaceStatistics'): InterfaceProfileRequest.FromString,
  }
  response_serializers = {
    ('com.brocade.telemetry.interface.InterfaceService', 'ListInterfaceStatistics'): InterfaceProfileResponse.SerializeToString,
  }
  method_implementations = {
    ('com.brocade.telemetry.interface.InterfaceService', 'ListInterfaceStatistics'): face_utilities.unary_stream_inline(servicer.ListInterfaceStatistics),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_InterfaceService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('com.brocade.telemetry.interface.InterfaceService', 'ListInterfaceStatistics'): InterfaceProfileRequest.SerializeToString,
  }
  response_deserializers = {
    ('com.brocade.telemetry.interface.InterfaceService', 'ListInterfaceStatistics'): InterfaceProfileResponse.FromString,
  }
  cardinalities = {
    'ListInterfaceStatistics': cardinality.Cardinality.UNARY_STREAM,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'com.brocade.telemetry.interface.InterfaceService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
