# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/brocade_systemutilization.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/brocade_systemutilization.proto',
  package='com.brocade.telemetry.systemutilization',
  syntax='proto3',
  serialized_pb=_b('\n&protos/brocade_systemutilization.proto\x12\'com.brocade.telemetry.systemutilization\"7\n\x1fSystemUtilizationProfileRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\"\xfd\x03\n SystemUtilizationProfileResponse\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x1b\n\x13total_system_memory\x18\x02 \x01(\r\x12\x19\n\x11total_used_memory\x18\x03 \x01(\r\x12\x19\n\x11total_free_memory\x18\x04 \x01(\r\x12\x15\n\rcached_memory\x18\x05 \x01(\r\x12\x0f\n\x07\x62uffers\x18\x06 \x01(\r\x12\x18\n\x10user_free_memory\x18\x07 \x01(\r\x12\x1a\n\x12kernel_free_memory\x18\x08 \x01(\r\x12\x19\n\x11total_swap_memory\x18\t \x01(\r\x12\x1e\n\x16total_free_swap_memory\x18\n \x01(\r\x12\x1e\n\x16total_used_swap_memory\x18\x0b \x01(\r\x12\x14\n\x0cuser_process\x18\x0c \x01(\r\x12\x16\n\x0esystem_process\x18\r \x01(\r\x12\x15\n\rniced_process\x18\x0e \x01(\r\x12\x0e\n\x06iowait\x18\x0f \x01(\r\x12\x14\n\x0chw_interrupt\x18\x10 \x01(\r\x12\x14\n\x0csw_interrupt\x18\x11 \x01(\r\x12\x12\n\nidle_state\x18\x12 \x01(\r\x12\x12\n\nsteal_time\x18\x13 \x01(\r\x12\x0e\n\x06uptime\x18\x14 \x01(\r2\xd7\x01\n\x18SystemUtilizationService\x12\xba\x01\n\x1fListSystemUtilizationStatistics\x12H.com.brocade.telemetry.systemutilization.SystemUtilizationProfileRequest\x1aI.com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse\"\x00\x30\x01\x42\x02H\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SYSTEMUTILIZATIONPROFILEREQUEST = _descriptor.Descriptor(
  name='SystemUtilizationProfileRequest',
  full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileRequest.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=138,
)


_SYSTEMUTILIZATIONPROFILERESPONSE = _descriptor.Descriptor(
  name='SystemUtilizationProfileResponse',
  full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_system_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_system_memory', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_used_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_used_memory', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_free_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_free_memory', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cached_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.cached_memory', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffers', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.buffers', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_free_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.user_free_memory', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_free_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.kernel_free_memory', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_swap_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_swap_memory', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_free_swap_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_free_swap_memory', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_used_swap_memory', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.total_used_swap_memory', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_process', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.user_process', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_process', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.system_process', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='niced_process', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.niced_process', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iowait', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.iowait', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hw_interrupt', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.hw_interrupt', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sw_interrupt', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.sw_interrupt', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idle_state', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.idle_state', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steal_time', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.steal_time', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse.uptime', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=650,
)

DESCRIPTOR.message_types_by_name['SystemUtilizationProfileRequest'] = _SYSTEMUTILIZATIONPROFILEREQUEST
DESCRIPTOR.message_types_by_name['SystemUtilizationProfileResponse'] = _SYSTEMUTILIZATIONPROFILERESPONSE

SystemUtilizationProfileRequest = _reflection.GeneratedProtocolMessageType('SystemUtilizationProfileRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMUTILIZATIONPROFILEREQUEST,
  __module__ = 'protos.brocade_systemutilization_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.systemutilization.SystemUtilizationProfileRequest)
  ))
_sym_db.RegisterMessage(SystemUtilizationProfileRequest)

SystemUtilizationProfileResponse = _reflection.GeneratedProtocolMessageType('SystemUtilizationProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMUTILIZATIONPROFILERESPONSE,
  __module__ = 'protos.brocade_systemutilization_pb2'
  # @@protoc_insertion_point(class_scope:com.brocade.telemetry.systemutilization.SystemUtilizationProfileResponse)
  ))
_sym_db.RegisterMessage(SystemUtilizationProfileResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\002'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class SystemUtilizationServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListSystemUtilizationStatistics = channel.unary_stream(
        '/com.brocade.telemetry.systemutilization.SystemUtilizationService/ListSystemUtilizationStatistics',
        request_serializer=SystemUtilizationProfileRequest.SerializeToString,
        response_deserializer=SystemUtilizationProfileResponse.FromString,
        )


class SystemUtilizationServiceServicer(object):

  def ListSystemUtilizationStatistics(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SystemUtilizationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListSystemUtilizationStatistics': grpc.unary_stream_rpc_method_handler(
          servicer.ListSystemUtilizationStatistics,
          request_deserializer=SystemUtilizationProfileRequest.FromString,
          response_serializer=SystemUtilizationProfileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.brocade.telemetry.systemutilization.SystemUtilizationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaSystemUtilizationServiceServicer(object):
  def ListSystemUtilizationStatistics(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaSystemUtilizationServiceStub(object):
  def ListSystemUtilizationStatistics(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()


def beta_create_SystemUtilizationService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('com.brocade.telemetry.systemutilization.SystemUtilizationService', 'ListSystemUtilizationStatistics'): SystemUtilizationProfileRequest.FromString,
  }
  response_serializers = {
    ('com.brocade.telemetry.systemutilization.SystemUtilizationService', 'ListSystemUtilizationStatistics'): SystemUtilizationProfileResponse.SerializeToString,
  }
  method_implementations = {
    ('com.brocade.telemetry.systemutilization.SystemUtilizationService', 'ListSystemUtilizationStatistics'): face_utilities.unary_stream_inline(servicer.ListSystemUtilizationStatistics),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_SystemUtilizationService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('com.brocade.telemetry.systemutilization.SystemUtilizationService', 'ListSystemUtilizationStatistics'): SystemUtilizationProfileRequest.SerializeToString,
  }
  response_deserializers = {
    ('com.brocade.telemetry.systemutilization.SystemUtilizationService', 'ListSystemUtilizationStatistics'): SystemUtilizationProfileResponse.FromString,
  }
  cardinalities = {
    'ListSystemUtilizationStatistics': cardinality.Cardinality.UNARY_STREAM,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'com.brocade.telemetry.systemutilization.SystemUtilizationService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
