# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/TelemetrySystemData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/TelemetrySystemData.proto',
  package='telemetry_system_stats',
  syntax='proto3',
  serialized_pb=_b('\n protos/TelemetrySystemData.proto\x12\x16telemetry_system_stats\":\n\"BrocadeTelemetrySystemData_request\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\"\xe1\x03\n#BrocadeTelemetrySystemData_response\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x1b\n\x13total_system_memory\x18\x02 \x01(\r\x12\x16\n\x0etotal_used_mem\x18\x03 \x01(\r\x12\x16\n\x0etotal_free_mem\x18\x04 \x01(\r\x12\x12\n\ncached_mem\x18\x05 \x01(\r\x12\x0f\n\x07\x62uffers\x18\x06 \x01(\r\x12\x15\n\ruser_free_mem\x18\x07 \x01(\r\x12\x17\n\x0fkernel_free_mem\x18\x08 \x01(\r\x12\x17\n\x0ftotalSwapMemory\x18\t \x01(\r\x12\x1b\n\x13totalFreeSwapMemory\x18\n \x01(\r\x12\x18\n\x10totalSwapMemUsed\x18\x0b \x01(\r\x12\x13\n\x0buserProcess\x18\x0c \x01(\r\x12\x15\n\rsystemProcess\x18\r \x01(\r\x12\x14\n\x0cnicedprocess\x18\x0e \x01(\r\x12\x0e\n\x06iowait\x18\x0f \x01(\r\x12\x14\n\x0chw_interrupt\x18\x10 \x01(\r\x12\x14\n\x0csw_interrupt\x18\x11 \x01(\r\x12\x11\n\tidleState\x18\x12 \x01(\r\x12\x11\n\tstealTime\x18\x13 \x01(\r\x12\x0e\n\x06uptime\x18\x14 \x01(\r2\xc0\x01\n\"BrocadeTelemetrySystemData_service\x12\x99\x01\n\x1a\x42rocadeTelemetrySystemData\x12:.telemetry_system_stats.BrocadeTelemetrySystemData_request\x1a;.telemetry_system_stats.BrocadeTelemetrySystemData_response\"\x00\x30\x01\x42\x02H\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BROCADETELEMETRYSYSTEMDATA_REQUEST = _descriptor.Descriptor(
  name='BrocadeTelemetrySystemData_request',
  full_name='telemetry_system_stats.BrocadeTelemetrySystemData_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_request.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=118,
)


_BROCADETELEMETRYSYSTEMDATA_RESPONSE = _descriptor.Descriptor(
  name='BrocadeTelemetrySystemData_response',
  full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_system_memory', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.total_system_memory', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_used_mem', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.total_used_mem', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_free_mem', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.total_free_mem', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cached_mem', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.cached_mem', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffers', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.buffers', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_free_mem', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.user_free_mem', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_free_mem', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.kernel_free_mem', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalSwapMemory', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.totalSwapMemory', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalFreeSwapMemory', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.totalFreeSwapMemory', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalSwapMemUsed', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.totalSwapMemUsed', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userProcess', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.userProcess', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='systemProcess', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.systemProcess', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nicedprocess', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.nicedprocess', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iowait', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.iowait', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hw_interrupt', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.hw_interrupt', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sw_interrupt', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.sw_interrupt', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idleState', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.idleState', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stealTime', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.stealTime', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='telemetry_system_stats.BrocadeTelemetrySystemData_response.uptime', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=602,
)

DESCRIPTOR.message_types_by_name['BrocadeTelemetrySystemData_request'] = _BROCADETELEMETRYSYSTEMDATA_REQUEST
DESCRIPTOR.message_types_by_name['BrocadeTelemetrySystemData_response'] = _BROCADETELEMETRYSYSTEMDATA_RESPONSE

BrocadeTelemetrySystemData_request = _reflection.GeneratedProtocolMessageType('BrocadeTelemetrySystemData_request', (_message.Message,), dict(
  DESCRIPTOR = _BROCADETELEMETRYSYSTEMDATA_REQUEST,
  __module__ = 'protos.TelemetrySystemData_pb2'
  # @@protoc_insertion_point(class_scope:telemetry_system_stats.BrocadeTelemetrySystemData_request)
  ))
_sym_db.RegisterMessage(BrocadeTelemetrySystemData_request)

BrocadeTelemetrySystemData_response = _reflection.GeneratedProtocolMessageType('BrocadeTelemetrySystemData_response', (_message.Message,), dict(
  DESCRIPTOR = _BROCADETELEMETRYSYSTEMDATA_RESPONSE,
  __module__ = 'protos.TelemetrySystemData_pb2'
  # @@protoc_insertion_point(class_scope:telemetry_system_stats.BrocadeTelemetrySystemData_response)
  ))
_sym_db.RegisterMessage(BrocadeTelemetrySystemData_response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\002'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class BrocadeTelemetrySystemData_serviceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BrocadeTelemetrySystemData = channel.unary_stream(
        '/telemetry_system_stats.BrocadeTelemetrySystemData_service/BrocadeTelemetrySystemData',
        request_serializer=BrocadeTelemetrySystemData_request.SerializeToString,
        response_deserializer=BrocadeTelemetrySystemData_response.FromString,
        )


class BrocadeTelemetrySystemData_serviceServicer(object):

  def BrocadeTelemetrySystemData(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BrocadeTelemetrySystemData_serviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BrocadeTelemetrySystemData': grpc.unary_stream_rpc_method_handler(
          servicer.BrocadeTelemetrySystemData,
          request_deserializer=BrocadeTelemetrySystemData_request.FromString,
          response_serializer=BrocadeTelemetrySystemData_response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'telemetry_system_stats.BrocadeTelemetrySystemData_service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaBrocadeTelemetrySystemData_serviceServicer(object):
  def BrocadeTelemetrySystemData(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaBrocadeTelemetrySystemData_serviceStub(object):
  def BrocadeTelemetrySystemData(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()


def beta_create_BrocadeTelemetrySystemData_service_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('telemetry_system_stats.BrocadeTelemetrySystemData_service', 'BrocadeTelemetrySystemData'): BrocadeTelemetrySystemData_request.FromString,
  }
  response_serializers = {
    ('telemetry_system_stats.BrocadeTelemetrySystemData_service', 'BrocadeTelemetrySystemData'): BrocadeTelemetrySystemData_response.SerializeToString,
  }
  method_implementations = {
    ('telemetry_system_stats.BrocadeTelemetrySystemData_service', 'BrocadeTelemetrySystemData'): face_utilities.unary_stream_inline(servicer.BrocadeTelemetrySystemData),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_BrocadeTelemetrySystemData_service_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('telemetry_system_stats.BrocadeTelemetrySystemData_service', 'BrocadeTelemetrySystemData'): BrocadeTelemetrySystemData_request.SerializeToString,
  }
  response_deserializers = {
    ('telemetry_system_stats.BrocadeTelemetrySystemData_service', 'BrocadeTelemetrySystemData'): BrocadeTelemetrySystemData_response.FromString,
  }
  cardinalities = {
    'BrocadeTelemetrySystemData': cardinality.Cardinality.UNARY_STREAM,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'telemetry_system_stats.BrocadeTelemetrySystemData_service', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
